# This is too much, it leads to too much line wrapping when using 2 editors side by side
# (in VSC with minimap enabled and explorer open).
#max_width = 120

# This should lead to fewer linebreaks in code like this:
# `self.gs.players.spawn_at(...).unwrap()`.
chain_width = 80
fn_call_width = 80

# This is another candidate for increase
#single_line_if_else_max_width
